# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_positive_elements <- function(Y, X, W) {
    .Call('_robfpca_get_positive_elements', PACKAGE = 'robfpca', Y, X, W)
}

IRLScpp <- function(Y, X, weight_ = NULL, maxit = 30L, tol = 0.0001, k = 1.345) {
    .Call('_robfpca_IRLScpp', PACKAGE = 'robfpca', Y, X, weight_, maxit, tol, k)
}

locpolysmooth <- function(Lt, Ly, newt, kernel = "epanechnikov", bw = 0.1, k = 1.345, deg = 1L) {
    .Call('_robfpca_locpolysmooth', PACKAGE = 'robfpca', Lt, Ly, newt, kernel, bw, k, deg)
}

order_ <- function(x) {
    .Call('_robfpca_order_', PACKAGE = 'robfpca', x)
}

weighted_quantile_cpp <- function(dat, weights, p) {
    .Call('_robfpca_weighted_quantile_cpp', PACKAGE = 'robfpca', dat, weights, p)
}

weighted_quantile_top_cpp <- function(dat, weights, p) {
    .Call('_robfpca_weighted_quantile_top_cpp', PACKAGE = 'robfpca', dat, weights, p)
}

wrm_fit <- function(xdat, ydat, x0, weight_vec) {
    .Call('_robfpca_wrm_fit', PACKAGE = 'robfpca', xdat, ydat, x0, weight_vec)
}

get_kernel <- function(x_i, x, h, method) {
    .Call('_robfpca_get_kernel', PACKAGE = 'robfpca', x_i, x, h, method)
}

wrm_smooth_cpp <- function(x, y, h, xgrid, kernel) {
    .Call('_robfpca_wrm_smooth_cpp', PACKAGE = 'robfpca', x, y, h, xgrid, kernel)
}

huber_cpp <- function(y, k = 1.5, tol = 1e-6) {
    .Call('_robfpca_huber_cpp', PACKAGE = 'robfpca', y, k, tol)
}

mean_Mest <- function(X) {
    .Call('_robfpca_mean_Mest', PACKAGE = 'robfpca', X)
}

cov_Mest <- function(X) {
    .Call('_robfpca_cov_Mest', PACKAGE = 'robfpca', X)
}

