# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fitdistr_cpp <- function(x, densfun, df = 3L) {
    .Call(`_robfpca_fitdistr_cpp`, x, densfun, df)
}

locScaleM_cpp <- function(x, psi, na_rm = 1L) {
    .Call(`_robfpca_locScaleM_cpp`, x, psi, na_rm)
}

quantile_cpp <- function(x, probs) {
    .Call(`_robfpca_quantile_cpp`, x, probs)
}

get_sigma2_rob_cpp <- function(v) {
    .Call(`_robfpca_get_sigma2_rob_cpp`, v)
}

cor_gk_cpp <- function(X, type = "huber", MM = 1L, df = 3L) {
    .Call(`_robfpca_cor_gk_cpp`, X, type, MM, df)
}

